# fly.toml app configuration file generated for sori on 2024-02-08T23:00:12-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sori'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  DISCORD_TOKEN = "PLACEHOLDER"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
