name: Perform Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_quality_analysis:
    name: Analyze Code for Quality Issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Source Code
        uses: actions/checkout@v4

      - name: Install Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: "latest"

      - name: Execute Code Quality Analysis
        run: biome ci .
