name: Deploy Application to Fly.io

on:
  workflow_run:
    workflows: ["Perform Tests"]
    branches: [main]
    types: [completed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy Application to Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Application via Docker
        run: flyctl deploy