name: Perform Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  perform-tests:
    name: Perform Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bun CLI
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun test
