name: Perform Tests

on:
  workflow_run:
    workflows: ["Perform Code Quality Checks"]
    branches: [main]
    types: [completed]

jobs:
  perform-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Perform Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bun CLI
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun test
